### ISSUE TITLE
scopeBehaviour: 'global' not remove :global() decl on rule

### ISSUE THREAD

**Issue by futurist** [css-modules/postcss-modules#30]
When using `scopeBehaviour: 'global' ` for below css rule:
```css
body:global(.noselect){ user-select:none }
```

The `:global` part is not removed, which result in invalid css selector.

**Comment by outpunk** [comment]
You have to place a space before `:global`, like this: `body :global(.noselect) { user-select:none }`. Otherwise it will be processed as pseudo-class.

**Comment by futurist** [comment]
tried place a space before ` :global`, result is same. And it's really worked when no space, if I use behaviour `local`

**Comment by outpunk** [comment]
Oh, I've got it. I think, it's not a good idea to use `:global` when it's the default behaviour. Just write `body .noselect { user-select:none }`.

**Comment by StarpTech** [comment]
I can reproduce it.

```css
:global .page {
  padding: 20px;
}
```

produces this in `scopeBehaviour: local` scope

```css
.page {
  padding: 20px;
}
```

but this in `scopeBehaviour: global` scope.

```css
.page {
  padding: 20px;
}
```
