### ISSUE TITLE
Should be a way to do not call all postcss processing.

### ISSUE THREAD

**Issue by btd** [css-modules/postcss-modules#47]
[At](https://github.com/css-modules/postcss-modules/blob/master/src/index.js#L29-L30) You get all plugins for later execution. In this case all postcss processing happen twice, and because of this sometimes with specific set of plugins css rulls appeared twice. I understand why this was done (to make imports work), but it could be easy fixed (iirc), just by moving postcss-modules to the end of plugins array.
Easy reproducible example:
```js
const postCssModules = require('postcss-modules');
const postCssAutoreset = require('postcss-autoreset');

const postcss = require('postcss');

const postCssPlugins = [
  postCssAutoreset,
  postCssModules({
    getJSON: function(cssFileName, json) {}
  }),
];

const css = `
.widget_editor {
  display: block;
}
`;

postcss(postCssPlugins)
    .process(css, { from: 'src/app.css', to: 'app.css' })
    .then(function(result) {
      console.log('RESULT', result.css)
    })

```

You will something like this:
```css
._widget_editor_1w0o5_2,
._widget_editor_1w0o5_2 {
  all: initial;
}
._widget_editor_1w0o5_2 {
  all: initial;
}
._widget_editor_1w0o5_2 {
  display: block;
}

```
