### ISSUE TITLE
composes providing undefined classname in output json

### ISSUE THREAD

**Issue by Tomdye** [css-modules/postcss-modules#52]
I'm trying to use composes in my css file with the postcss-modules plugin but the outputted json for tabpanel.css.json includes an `undefined` class name rather than the `button` class name I am expecting.

Input tabpanel/tabPanel.css
``` css
.tabPanelTab {
	composes: button from "../button/button.css";
	display: inline-block;
	margin: 0;
	border: none;
	border-right: 1px solid black;
}
```

Input button/button/.css
``` css
.button {
	background: red;
	padding: 10px;
	border: 1px solid black;
}

.button:hover {
	background: green;
}
```

Output tabpanel/tabPanel.css
``` css
.button__button__button__3sp2V__1btJf {
	background: red;
	padding: 10px;
	border: 1px solid black;
}
.button__button__button__3sp2V__1btJf:hover {
	background: green;
}
.tabpanel__tabPanelTab__2e0ic {
	display: inline-block;
	margin: 0;
	border: none;
	border-right: 1px solid black;
}
```

Output tabpanel/tabPanel.css.json JSON
``` json
{"tabPanelTab":"tabpanel__tabPanelTab__2e0ic undefined"}
```

I am using the latest `grunt-postcss` version along with the latest `postcss-modules` version.
My grunt config is as follows:

``` javascript
	postcss: {
			options: {
				map: true,
				processors: [
					require('postcss-modules')({
						generateScopedName: '[name]__[local]__[hash:base64:5]'
					})
				]
			},
			dist: {
				files: [ {
					expand: true,
					src: 'dist/umd/**/*.css'
				} ]
			}
		}
```

** EDIT **
If I manually specify the file order to load the `tabPanel.css` before `button.css` the outputted json is as expected. It appears that the reference to the class is lost once the file that is being imported via `composes` is processed by postCss.
