### ISSUE TITLE
`generateScopedName.js`  ie6 bug

### ISSUE THREAD

**Issue by cjg125** [css-modules/postcss-modules#73]
```js
......
return `_${ name }_${ hash }_${ lineNumber }`;
```

ie6  “_” prefix to be unsupported

**Comment by marcobiedermann** [comment]
@cjg125 
IE6? Really? o.O

**Comment by cjg125** [comment]
@marcobiedermann yes ~~  
```css
._container{
background:red
}
```
