### ISSUE TITLE
like styled-jsx

### ISSUE THREAD

**Issue by Topthinking** [css-modules/postcss-modules#76]
```css
.demo{
 color:red;
}
```

```jsx
.demo.jsx-123456{
 color:red;
}
```

What can I do with this format?

That is, you can automatically add a class selector to all the selectors.
