### ISSUE TITLE
How do I exclude global selectors (such as html and body)?

### ISSUE THREAD

**Issue by wickedev** [css-modules/postcss-modules#95]
I am creating a React component using create-react-library, which uses postcss-modules with rollup. I am trying to use the css module to create a bootstrap wrapper, which contains the following css to pollute the global. Is there a way to get rid of it?

```css
html {
   font-family: sans-serif;
   line-height: 1.15;
   -webkit-text-size-adjust: 100%;
   -webkit-tap-highlight-color: rgba (0, 0, 0, 0);
}
```

Thanks for reading.
